### ISSUE TITLE
Feature_Radar chart with the job offer

### ISSUE THREAD

**Issue by OscarArroyoVega** [OscarArroyoVega/LLM_Resume_Analyser_Unify#7]
radar chart represetation of resume and job offer  

![Image](https://github.com/OscarArroyoVega/LLM_Resume_Analyser_Unify/assets/103512255/744f01f3-9194-48f7-b213-67acc18ab209)

**Comment by OscarArroyoVega** [comment]
https://www.pythoncharts.com/matplotlib/radar-charts/

**Comment by adityathenerd** [comment]
Hey @OscarArroyoVega , What will this plot indicate exactly, is it the keywords extracted from the job description?

**Comment by OscarArroyoVega** [comment]
Hellow @adityathenerd ,the image was just a reference of a desired output. Yes, I think it should represent the scores the Resume obtains in each category against the job offer. Now i am working on:
(1)Doing one task per prompt to extract data or raw results, 
(2 )parsing the results in a consistant way. 
(3)Then building a report (charts + text+ ..) from the obtained results.

**Comment by OscarArroyoVega** [comment]
Hellow @adityathenerd ,the image was just a reference of a desired output. Yes, I think it should represent the scores the Resume obtains in each category against the job offer. Now I am working on:
(1)Doing one task per prompt to extract data or raw results, 
(2 )parsing the results in a consistant way. 
(3)Then building a report (charts + text+ ..) from the obtained results.
